name: deploy

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: "placeholder"
          
      - name: Add known known_hosts
        run: ssh-keyscan -p ${{secrets.SSH_PORT}} -H ${{secrets.SSH_HOST}} >> ~/.ssh/known_hosts

      - name: Sync files to remote
        run: rsync -avz --force --delete -e 'ssh -p ${{secrets.SSH_PORT}}' ./api/ ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:/home/${{secrets.SSH_USER}}/api

      - name: Deploy docker on remote
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          port: ${{secrets.SSH_PORT}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            # Stop all running Docker Containers
            cd /home/${{secrets.SSH_USER}}/api

            docker-compose up -d --force-recreate --build
            
      - name: Discord Notification
        if: always()
        uses: SebastiaanZ/github-status-embed-for-discord@main
        with:
          webhook_id: '945323813007163432'  # Has to be provided as a string
          webhook_token: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{job.status}}

          pr_author_login: ${{ github.event.pull_request.user.login }}
          pr_number: ${{ github.event.pull_request.number }}
          pr_title: ${{ github.event.pull_request.title }}
          pr_source: ${{ github.event.pull_request.head.label }}
  
  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      # Runs a single command using the runners shell
      - name: run yarn install
        run: yarn install

      - name: run yarn generate
        run: yarn generate

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa # optional
          known_hosts: "placeholder"

      - name: Add known known_hosts
        run: ssh-keyscan -p ${{secrets.SSH_PORT}} -H ${{secrets.SSH_HOST}} >> ~/.ssh/known_hosts

      - name: Sync files with remote
        run: rsync -avz --force --delete -e 'ssh -p ${{secrets.SSH_PORT}}' ./dist/ ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:${{secrets.TARGET_DIR}}
      
      - name: Discord Notification
        if: always()
        uses: SebastiaanZ/github-status-embed-for-discord@main
        with:
          webhook_id: '945323813007163432'  # Has to be provided as a string
          webhook_token: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{job.status}}

          pr_author_login: ${{ github.event.pull_request.user.login }}
          pr_number: ${{ github.event.pull_request.number }}
          pr_title: ${{ github.event.pull_request.title }}
          pr_source: ${{ github.event.pull_request.head.label }}
