# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  check-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      # Runs a single command using the runners shell
      - name: run yarn install
        run: yarn install

      - name: run yarn generate
        run: yarn generate
      
      - name: Discord Notification
        if: always()
        uses: SebastiaanZ/github-status-embed-for-discord@main
        with:
          webhook_id: '945323813007163432'  # Has to be provided as a string
          webhook_token: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{job.status}}

          pr_author_login: ${{ github.event.pull_request.user.login }}
          pr_number: ${{ github.event.pull_request.number }}
          pr_title: ${{ github.event.pull_request.title }}
          pr_source: ${{ github.event.pull_request.head.label }}
